// Server-safe permission/role catalog (no 'use client' directive).
// This is the source of truth for what permission strings exist and
// which system roles grant which permissions by default — imported
// by both server code (lib/rbac-seed.ts, Server Actions) and the
// client hook in lib/permissions.ts.

export const PERMISSIONS = {
  'dashboard.view': { name: 'dashboard.view', description: 'View dashboard', category: 'Dashboard' },
  'users.view': { name: 'users.view', description: 'View users', category: 'Users' },
  'users.create': { name: 'users.create', description: 'Create users', category: 'Users' },
  'users.update': { name: 'users.update', description: 'Update users', category: 'Users' },
  'users.delete': { name: 'users.delete', description: 'Delete users', category: 'Users' },
  'roles.view': { name: 'roles.view', description: 'View roles', category: 'Roles' },
  'roles.create': { name: 'roles.create', description: 'Create roles', category: 'Roles' },
  'roles.update': { name: 'roles.update', description: 'Update roles', category: 'Roles' },
  'roles.delete': { name: 'roles.delete', description: 'Delete roles', category: 'Roles' },
  'organizations.view': { name: 'organizations.view', description: 'View organizations', category: 'Organizations' },
  'organizations.update': { name: 'organizations.update', description: 'Update organizations', category: 'Organizations' },
  'files.view': { name: 'files.view', description: 'View files', category: 'Files' },
  'files.upload': { name: 'files.upload', description: 'Upload files', category: 'Files' },
  'files.download': { name: 'files.download', description: 'Download files', category: 'Files' },
  'files.update': { name: 'files.update', description: 'Update files', category: 'Files' },
  'files.delete': { name: 'files.delete', description: 'Delete files', category: 'Files' },
  'files.share': { name: 'files.share', description: 'Share files', category: 'Files' },
  'files.manage': { name: 'files.manage', description: 'Manage files', category: 'Files' },
  'leads.view': { name: 'leads.view', description: 'View leads', category: 'Leads' },
  'leads.create': { name: 'leads.create', description: 'Create leads', category: 'Leads' },
  'leads.update': { name: 'leads.update', description: 'Update leads', category: 'Leads' },
  'leads.delete': { name: 'leads.delete', description: 'Delete leads', category: 'Leads' },
  'leads.export': { name: 'leads.export', description: 'Export leads', category: 'Leads' },
  'companies.view': { name: 'companies.view', description: 'View companies', category: 'Companies' },
  'companies.create': { name: 'companies.create', description: 'Create companies', category: 'Companies' },
  'companies.update': { name: 'companies.update', description: 'Update companies', category: 'Companies' },
  'companies.delete': { name: 'companies.delete', description: 'Delete companies', category: 'Companies' },
  'contacts.view': { name: 'contacts.view', description: 'View contacts', category: 'Contacts' },
  'contacts.create': { name: 'contacts.create', description: 'Create contacts', category: 'Contacts' },
  'contacts.update': { name: 'contacts.update', description: 'Update contacts', category: 'Contacts' },
  'contacts.delete': { name: 'contacts.delete', description: 'Delete contacts', category: 'Contacts' },
  'deals.view': { name: 'deals.view', description: 'View deals', category: 'Deals' },
  'deals.create': { name: 'deals.create', description: 'Create deals', category: 'Deals' },
  'deals.update': { name: 'deals.update', description: 'Update deals', category: 'Deals' },
  'deals.delete': { name: 'deals.delete', description: 'Delete deals', category: 'Deals' },
  'deals.export': { name: 'deals.export', description: 'Export deals', category: 'Deals' },
  'meetings.view': { name: 'meetings.view', description: 'View meetings', category: 'Meetings' },
  'meetings.create': { name: 'meetings.create', description: 'Create meetings', category: 'Meetings' },
  'meetings.update': { name: 'meetings.update', description: 'Update meetings', category: 'Meetings' },
  'meetings.delete': { name: 'meetings.delete', description: 'Delete meetings', category: 'Meetings' },
  'field_visits.view': { name: 'field_visits.view', description: 'View field visits', category: 'Field Visits' },
  'field_visits.create': { name: 'field_visits.create', description: 'Create field visits', category: 'Field Visits' },
  'field_visits.update': { name: 'field_visits.update', description: 'Update field visits', category: 'Field Visits' },
  'reports.view': { name: 'reports.view', description: 'View reports', category: 'Reports' },
  'reports.export': { name: 'reports.export', description: 'Export reports', category: 'Reports' },
  'team.view': { name: 'team.view', description: 'View own team data', category: 'Team' },
  'team.view_all': { name: 'team.view_all', description: 'View all team members and cross-employee data', category: 'Team' },
  'reports.submit': { name: 'reports.submit', description: 'Submit daily reports', category: 'Reports' },
  'reports.view_all': { name: 'reports.view_all', description: 'View all daily reports', category: 'Reports' },
  'ai.use': { name: 'ai.use', description: 'Use AI features', category: 'AI' },
  'settings.view': { name: 'settings.view', description: 'View settings', category: 'Settings' },
  'settings.manage': { name: 'settings.manage', description: 'Manage settings', category: 'Settings' },
  'audit_logs.view': { name: 'audit_logs.view', description: 'View audit logs', category: 'Audit Logs' },
} as const

export type PermissionKey = keyof typeof PERMISSIONS

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: Object.keys(PERMISSIONS) as PermissionKey[],
  ADMIN: [
    'dashboard.view',
    'users.view', 'users.create', 'users.update', 'users.delete',
    'roles.view', 'roles.create', 'roles.update', 'roles.delete',
    'organizations.view', 'organizations.update',
    'files.view', 'files.upload', 'files.download', 'files.update', 'files.delete', 'files.share', 'files.manage',
    'leads.view', 'leads.create', 'leads.update', 'leads.delete', 'leads.export',
    'companies.view', 'companies.create', 'companies.update', 'companies.delete',
    'contacts.view', 'contacts.create', 'contacts.update', 'contacts.delete',
    'deals.view', 'deals.create', 'deals.update', 'deals.delete', 'deals.export',
    'meetings.view', 'meetings.create', 'meetings.update', 'meetings.delete',
    'field_visits.view', 'field_visits.create', 'field_visits.update',
    'team.view', 'team.view_all',
    'reports.view', 'reports.export', 'reports.submit', 'reports.view_all',
    'ai.use',
    'settings.view', 'settings.manage',
    'audit_logs.view',
  ],
  MANAGER: [
    'users.view',
    'files.view', 'files.upload', 'files.download', 'files.share',
    'leads.view', 'leads.create', 'leads.update', 'leads.export',
    'companies.view', 'companies.create', 'companies.update',
    'contacts.view', 'contacts.create', 'contacts.update',
    'deals.view', 'deals.create', 'deals.update', 'deals.export',
    'meetings.view', 'meetings.create', 'meetings.update',
    'field_visits.view', 'field_visits.create', 'field_visits.update',
    'team.view', 'team.view_all',
    'reports.view', 'reports.submit', 'reports.view_all',
    'ai.use',
    'settings.view',
  ],
  SALES_MANAGER: [
    'files.view', 'files.upload', 'files.download', 'files.share',
    'leads.view', 'leads.create', 'leads.update', 'leads.export',
    'companies.view', 'companies.create', 'companies.update',
    'contacts.view', 'contacts.create', 'contacts.update',
    'deals.view', 'deals.create', 'deals.update', 'deals.export',
    'meetings.view', 'meetings.create', 'meetings.update',
    'field_visits.view', 'field_visits.create', 'field_visits.update',
    'team.view',
    'reports.view', 'reports.submit',
    'ai.use',
  ],
  SALES_EXECUTIVE: [
    'files.view', 'files.upload', 'files.download',
    'leads.view', 'leads.create', 'leads.update',
    'companies.view', 'companies.create', 'companies.update',
    'contacts.view', 'contacts.create', 'contacts.update',
    'deals.view', 'deals.create', 'deals.update',
    'meetings.view', 'meetings.create', 'meetings.update',
    'field_visits.view', 'field_visits.create', 'field_visits.update',
    'team.view',
    'reports.submit',
    'ai.use',
  ],
  MARKETING: [
    'files.view', 'files.upload', 'files.download',
    'leads.view', 'leads.create', 'leads.update',
    'companies.view', 'companies.create', 'companies.update',
    'team.view',
    'reports.view', 'reports.submit',
    'ai.use',
  ],
  HR: [
    'users.view',
    'team.view', 'team.view_all',
    'reports.view_all',
    'files.view', 'files.download',
    'settings.view',
  ],
  FINANCE: [
    'files.view', 'files.download',
    'reports.view', 'reports.export',
  ],
  VIEWER: [
    'team.view',
    'files.view', 'files.download',
    'leads.view',
    'companies.view',
    'contacts.view',
    'deals.view',
    'meetings.view',
    'field_visits.view',
  ],
}
