import type { UniversalReportDefinition } from '../types'

export function buildAiReport(opts: {
  title: string
  type: string
  content: string
  createdAt: string
  generatedByName: string
  organizationName?: string
}): UniversalReportDefinition {
  const typeLabel = opts.type.replace(/_/g, ' ')
  return {
    name: opts.title.replace(/[^a-zA-Z0-9]+/g, '-').slice(0, 48) || 'AI-Report',
    title: opts.title,
    subtitle: `${typeLabel} · grounded in live CRM data · scoped to your permissions`,
    periodLabel: new Date(opts.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
    metadata: {
      generatedAt: new Date(opts.createdAt).toISOString(),
      generatedBy: opts.generatedByName,
      organizationName: opts.organizationName,
    },
    sections: [
      {
        title: opts.title,
        description: `${typeLabel} — ${new Date(opts.createdAt).toLocaleString('en-IN')}`,
        text: opts.content,
      },
    ],
    footerNote: 'Generated by AI from your live CRM snapshot · verify critical figures before sharing externally.',
  }
}
