import 'server-only'
import { BaseTemplate, TextTemplate } from './base'

export interface AIReportReadyTemplateProps {
  reportTitle: string
  reportType: string
  generatedByName: string
  reportUrl: string
  organizationName: string
  summary?: string
}

export function AIReportReadyTemplate({
  reportTitle,
  reportType,
  generatedByName,
  reportUrl,
  organizationName,
  summary,
}: AIReportReadyTemplateProps): { html: string; text: string } {
  const typeLabels: Record<string, string> = {
    daily_summary: 'Daily Summary',
    team_management: 'Team Management Report',
    deal_analysis: 'Deal Analysis',
    lead_scoring: 'Lead Scoring Report',
    custom: 'Custom Report',
  }

  const typeLabel = typeLabels[reportType] || reportType

  const html = BaseTemplate({
    title: 'AI Report Ready',
    preheader: `Your ${typeLabel} "${reportTitle}" has been generated`,
    children: `
      <p>Hi there,</p>
      <p>Your AI-generated <strong>${typeLabel}</strong> has been completed in <strong>${organizationName}</strong>.</p>
      
      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 24px 0;">
        <p style="margin: 0 0 8px; font-size: 15px;"><strong>Report:</strong> ${reportTitle}</p>
        <p style="margin: 0 0 8px; font-size: 14px;"><strong>Type:</strong> ${typeLabel}</p>
        <p style="margin: 0; font-size: 14px; color: #64748b;">Generated by: ${generatedByName}</p>
      </div>
      
      ${summary ? `
        <div style="background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 16px; margin: 24px 0;">
          <p style="margin: 0 0 8px; font-size: 13px; font-weight: 600; color: #92400e;">AI Summary</p>
          <p style="margin: 0; font-size: 14px; color: #78350f;">${summary}</p>
        </div>
      ` : ''}
      
      <p>Review the report for insights and recommended actions.</p>
    `,
    cta: {
      text: 'View Report',
      url: reportUrl,
    },
  })

  const text = TextTemplate({
    title: 'AI Report Ready',
    children: `Hi there,\n\nYour AI-generated ${typeLabel} has been completed in ${organizationName}.\n\nReport: ${reportTitle}\nType: ${typeLabel}\nGenerated by: ${generatedByName}\n${summary ? `\nAI Summary: ${summary}\n` : ''}\nReview the report for insights.`,
    cta: {
      text: 'View Report',
      url: reportUrl,
    },
  })

  return { html, text }
}