import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft } from 'lucide-react'
import { MainLayout } from '@/components/layout'
import { PageHeader } from '@/components/crm/page-header'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Markdown } from '@/components/ai/markdown'
import { getReport } from '@/services/ai.service'
import { format } from 'date-fns'

export const metadata = { title: 'Report | Kawman ExAct' }

export default async function AIReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const report = await getReport(id)
  if (!report) notFound()

  return (
    <MainLayout>
      <div className="space-y-6 max-w-3xl">
        <Button asChild variant="ghost" size="sm" className="gap-1.5 -ml-2">
          <Link href="/ai/reports">
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to reports
          </Link>
        </Button>
        <PageHeader
          title={report.title}
          subtitle={`Generated by ${report.generatedByName} on ${format(new Date(report.createdAt), 'd MMM yyyy, h:mm a')}`}
        />
        <Card>
          <CardContent className="pt-6">
            <Markdown content={report.content} className="space-y-1 text-white/80" />
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  )
}
